### PR TITLE
Add net50 build

### PR DESCRIPTION
**Pull request by bbowyersmyth**
Builds both .net 4.7 and .net 5.0 although only 4.7 will be used for now.

### CODE REVIEW

**Comment by bbowyersmyth** [comment]
@0xC0000054 did you still want to support PDN 3.5?

**Comment by 0xC0000054** [comment]
> did you still want to support PDN 3.5?

I am open to dropping it.

The native code is the biggest issue with maintaining PDN 3.5.X compatibility, I currently build it with VS2010 to maintain the PDN 3.5.X OS support.
The Windows XP targeting pack is depreciated in VS2019, and I do not want the hassle of building the native libraries with two different compilers.

If someone wants to use the latest version of the WebP plugin with 3.5.X, they can build always build it themselves.

**Comment by bbowyersmyth** [comment]
Ok in that case how about creating a branch off the current master for 3.5 users and I remove the net35 build as part of this PR?

**Comment by 0xC0000054** [comment]
> Ok in that case how about creating a branch off the current master for 3.5 users and I remove the net35 build as part of this PR?

That would work.

Edit: I created a `pdn_3_5_X` branch.

**Comment by bbowyersmyth** [comment]
PR change pushed

**Pull request merged**
